### PR TITLE
Add connect command

### PR DESCRIPTION
**Pull request by yoheikikuta**
Created Connect command.
This is a naive implementation using standard outputs of Parameter command.
I'd like to discuss implementation designs (and whether this PR is useful or not in the first place).

### CODE REVIEW

**Comment by takahi-i** [comment]
Thank you very much for the valuable contribution @yoheikikuta 🙏 !!

**Comment by takahi-i** [comment]
Looks like CI fails since the linter deteted the following problems.

```
$ make lint
flake8 pf_manager tests
pf_manager/cli.py:100:1: E302 expected 2 blank lines, found 1
pf_manager/cli.py:106:1: E302 expected 2 blank lines, found 1
```

Can you please fix the problems. The linter would work in your environment.

**Comment by yoheikikuta** [comment]
Changed some scripts to pass lint checks.
Sorry about that.

**Comment by takahi-i** [comment]
Great @yoheikikuta ! Would be appreciate it if you add the description on connect subcommand in README 🙏 🙇

**Comment by yoheikikuta** [comment]
I squashed my commits (sorry one previous commit includes me as committers but I think it's not a big problem).
I will also add descriptions on README.

**Comment by yoheikikuta** [comment]
Added :muscle:

**Comment by takahi-i** [comment]
Fascinating @yoheikikuta! Thank you very much for the valuable contribution as always!

**Pull request merged**
